realgud/realgud

realgud/common/core.el, realgud/debugger/gdb/gdb.el, test/test-gdb-core.el
I incorporated your comments and also wrote a test for realgud:gdb-parse-cmd-args. I would really like to write more complex tests like:
1. start gdb
2. check which buffers are created
... but I don't know how its done.
Best regards,
Kilian.
=> Fix several issues when calling gdb, Fixes #59

realgud/debugger/ipdb/core.el, realgud/debugger/ipdb/ipdb.el, test/test-ipdb.el
Not perfect but probably better.
=> Ipdb complete

realgud/debugger/ipdb/init.el, realgud/debugger/pdb/init.el
Connects to #82. This is a first step; there are a few issues left to be discussed in that issue.
=> Improve command mappings in pdb-command-hash

realgud/common/cmds.el
In safe mode, prompt and offer a tip on how to disable safe mode before
running "continue".
Connected to #82.
=> Add a "safe mode" setting (on by default)

realgud/common/cmds.el
Instead of passing a default template in each individual call, collect
all default templates in a single hash.  Take that opportunity to clean
up the two 'cmd-*-no-args' implementations.
@rocky, what do you think of this refactoring? I think it'll be a convenient way for authors to look up what commands we support, too.
=> Further refactor cmds.el

.gitignore, realgud-recursive-autoloads.el, realgud.el
=> Revert "Revert "Manually generate "recursive" autoloads for subdirectories""

el-get-install.el
Follow-up to https://github.com/realgud/realgud/commit/b5d5f30780a2bcd13c90f3bf3643ef1509e8ee0b and https://github.com/realgud/realgud/commit/a8bd8678db59322dac1015576716c4ebb2c628df.
=> el-get-install.el: remove list-utils

realgud/common/helper.el
Otherwise `make check` can lead to this error: https://gist.github.com/dunn/ee1080dd3b32aaf8594d3c8368da7bde
=> common/helper: require cl

Makefile.am, realgud/common/buffer/backtrace.el, realgud/common/buffer/command.el, realgud/common/file.el, realgud/common/fringe.el, realgud/common/regexp.el, realgud/common/track.el, realgud/debugger/gdb/init.el, realgud/debugger/gub/init.el, realgud/debugger/jdb/core.el, realgud/debugger/nodejs/init.el, realgud/debugger/trepan/core.el, realgud/debugger/trepan2/core.el, realgud/debugger/trepanjs/init.el, realgud/lang/js.el, realgud/lang/python.el, test/test-file.el, test/test-loc-regexp-nodejs.el, test/test-regexp-gub.el, test/test-regexp-python.el, test/test-regexp-rdebug.el, test/test-regexp-trepan.el, test/test-track.el
Track column offsets when given. 
@cpitclaudel FYI review if you have time.
=> Column offsets

realgud/common/fringe.el
@cpitclaudel  thoughts?  See also https://emacs.stackexchange.com/questions/33847/how-to-dynamically-alter-defface-foreground-and-background
=> Simplify and perhaps generalize

realgud.el, test/test-realgud.el
Please review and let me know.
=> fixed unload; added ert-based tests for realgud

realgud/common/track.el
sorry i introduced an error by not passing enough arguments
=> fixed an error

realgud/common/utils.el
Solves https://github.com/realgud/realgud/issues/216
=> Check major mode with derived-mode-p

realgud/common/cmds.el, realgud/common/key.el, realgud/common/shortkey.el
Hi, 
Here is the code for issue #116. 
Thanks, 
-Crane
=> add key 'h' for cmd-until-here: continue until the current line

realgud/common/breakpoint-mode.el, realgud/common/buffer/breakpoint.el, realgud/common/buffer/command.el, realgud/common/buffer/helper.el, realgud/common/cmds.el, realgud/common/init.el, realgud/common/track.el, realgud/common/window.el, realgud/debugger/gdb/init.el, realgud/debugger/trepan3k/init.el, realgud/lang/python.el, test/regexp-helper.el, test/test-loc-regexp-gdb.el, test/test-regexp-trepan3k.el
=> Add a breakpoint buffer analogous to backtrace

README.md
Looks like the wiki page got moved.
=> Fix link to supported debuggers

realgud.el, realgud/common/buffer/command.el, realgud/common/buffer/helper.el, realgud/common/buffer/locals.el, realgud/common/cmds.el, realgud/common/custom.el, realgud/common/key.el, realgud/common/locals-mode.el, realgud/common/track.el, realgud/common/window.el, realgud/debugger/pdb/init.el
As we discussed, I'm opening pull request.
I'm setting it to draft as i want to introduce frame identification.
Once merged, this pr closes #191
=> Locals window v2.1

realgud/common/buffer/source.el, realgud/common/core.el, test/test-keymap-cleanup.el
Close #275. Close #65.
@rocky Please take a look if i'm not breaking something...
=> Fix #275. Add srcbuf-mode to allow cleaning up shortcuts at quit.

realgud/common/buffer/locals.el, realgud/common/custom.el, realgud/common/locals-mode.el
Show all values bu default and allow bulk show/hide
use list of variables as dumb id of function/frame. it's easy to implement and should work in most cases.
=> Final changes for initial version of loclas

realgud/common/locals-mode.el
Not sure if this is correct, but for me, realgud failed to load without this patch.
Thanks.
=> fix issue: failed to load file realgud/common/helper.

git2cl
=> Upgrade to GPLv3 in git2cl

README.md
I hate being the guy trying to correcting grammar but I could not pass this one. Since the first syllable of "extensible" is a vowel the quantifier should be "An" instead of "A"
=> Update README.md by changing a single quantifier
