realgud/common/core.el
The problem is as follows: the first time I start realgud in a session, realgud offers a reasonable default. For example. for python, on the first invocation, I get `pdb <filename>`.
However, on subsequent invocations (on different files), I get the same `pdb <original file name>`. This is rather inconvenient, especially when using savehist-mode.
Since the first history is very easily accessible (using `M-p` or `<kbd-up>`), maybe it would be better to default to the `<debugger-name> <file-name>` option? This PR implements this.
Additionally, I made sure to quote file names and to add completion via `read-shell-command`.
What do you think?
=> Improve completion and default value in realgud-query-cmdline

realgud/common/cmds.el, realgud/common/menu.el, realgud/common/shortkey.el
Part of #83. Btw, when I lookup the `C-c e` keybinding in realgud:gdb, I see this:
```
C-c e runs the command realgud:cmd-eval (found in
realgud:gdb-short-key-mode-map), which is an interactive Lisp function in
‘realgud/common/cmds.el’.
```
However, I couldn't track down `realgud:gdb-short-key-mode-map` or the code that sets this binding... where is it? (I wanted to add a small comment to it, noting that it could be disabled in a future release)
=> Improve eval: run on region if active, and fall back to prompting

realgud/common/cmds.el
Without it, "c" now just continues without prompting.
Discussed in #82.
=> Add a prefix arg to "continue" command

realgud/common/cmds.el
Interactively, these three commands now disable, enable, or delete a
breakpoint found on the current line, and only prompt for a breakpoint
number if they can't find one.
This default behavior is overridden in two cases:
* When a numeric prefix argument is given, in which case they use that
as the breakpoint number (consistent with current behavior)
* When a generic prefix argument is given, in which case they always
prompt, but offer a breakpoint number on the current line as the
default.
Closes #87.
=> Improve behavior of delete, enable, and disable

realgud/common/cmds.el
- Fix docstring of cmd-shell
- Remove unused arg of cmd-terminate
- Remove a call to local-set-key that affected the current buffer when
realgud was loaded
The last one connects to #83; that keybinding was going to the wrong keymap in most cases.
=> Small fixes in cmds.el

.gitignore, realgud-recursive-autoloads.el, realgud.el
Fixes #84; the discussion on emacs-dev concluded that this was the best solution. The commit is annoyingly large, but the only actual changes are in `realgud.el`.
After merging this, we'll need to update the MELPA recipe to include this file autoloads file. We could probably simplify it, too, so that future additions don't require additional changes.
This also adds a small maintenance burden: when we add new autoloads, we'll need to run `realgud--rebuild-recursive-autoloads`. This seems like an acceptable trade-off.
What do you think?
=> Manually generate "recursive" autoloads for subdirectories

realgud/common/buffer/source.el, realgud/common/shortkey.el
When enabling short-key-mode in an orphan source buffer (i.e. one that
isn't attached to a command buffer), prompt the user for a command
buffer to attach to instead of complaining (and complain only if there
is no available command buffer).
Additionally make shortkey-mode-setup more robust by restoring the
original local map properly disabling the toolbar after exiting.
Closes #36; thanks for the suggestion!
=> Automatically attach to a command buffer when enabling short-key-mode

realgud/debugger/ipdb/core.el
Fail gracefully if point isn't at prompt, and get prefix from iPython
instead of relying on bounds-of-thing-at-point.
Fixes #75.
=> Improve IPDB completion

realgud/common/track.el, realgud/debugger/gdb/init.el
Instead of introducing a separate regexp for the "multiple breakpoints removed at once" case, the idea is that we allow the string of breakpoints to contain multiple numbers. We parse them out, and we disable all relevant breakpoints.
The parsing is extremely liberal: it just splices out anything that isn't a number.
I took this opportunity to refactor the error message that multiple functions produced, into a single message.
I'm a bit uneasy touching parts of the core infrastructure, so please review and test :)
=> Allow realgud-track-bp-delete to recognize multiple breakpoints

realgud/common/bp.el
Default to a (larger) rectangle instead of a circle, and highlight full
line on active breakpoints.
Addresses parts of the discussion in #102.
=> Improve visibility of breakpoints

realgud/common/cmds.el, realgud/common/send.el
This gives `break` and `clear` a more interesting C-u interface, which prompts for a line number with plain C-u and uses the given number with C-number.
I had to make a small extension to format-command, to allow overriding flags: this seems much better than changing all of break commands in all debuggers to use `%p` instead of `%l`. What now happens is that the call to `run-cmd` gets wrapped in a let-binding that overrides the meaning of `%l` for the duration of that call.
I took that opportunity to clean up commands which took optional arguments but did not use them.
=> Further cleanups of cmds.el + improved C-u behaviour

realgud/common/cmds.el
Although quit for gdb should be done via a non-prompting quit which remains to be done, my take is to move forward and deal with that some other time. @cpitclaudel  ?
=> Confirm on debugger quit.

realgud/common/key.el
The realgud-populate-common-fn-keys-standard map function was always
run, even when realgud-populate-common-fn-keys-function was configured
as nil. Fixes #129
=> Don't bind standard keys when disabled by config

realgud/common/file.el
I personally don't like `compilation-find-file` prompting me at
the start of every gdb session when it can't find a relative
breakpoint in a large code base at a separate folder.
BTW, it _will_ find it later, when gdb outputs the complete path when it stops at mentioned breakpoint
=> Customizable "search for this (relative) bp file"

realgud/debugger/trepan2/core.el
DEBUGGER-NAME in trepan2-suggest-invocation was not being considered.
=> Honor debugger-name in trepan2-suggest-invocation

realgud/common/buffer/backtrace.el, test/test-bt-trepan2.el
match-end and match-begin is overridden in realgud:file-loc-from-line.
It is better to store them in variables.
=> Fix infinite loop in realgud:backtrace-init

realgud/common/cmds.el, realgud/common/shortkey.el
a nice little shortcut in shortkey mode, when you hit E it will immediately eval whats under the point
=> add eval at point and bind it to E in shortkey mode

realgud/common/track.el, test/test-track.el
i was working on https://github.com/realgud/realgud/issues/180 and in an effort to understand what is going on I did an extract-method on two breakpoint related sections of realgud:track-from-region.  thought it was worth creating a pull request of it.
Do you remember what 
`	      (realgud-track-bp-enable-disable text-sans-loc
(realgud-cmdbuf-pat "brkpt-enable")
't)
(realgud-track-bp-enable-disable text-sans-loc
(realgud-cmdbuf-pat "brkpt-disable")
nil)
`
is suppose to do?  it seems like this might have the same purpose of the two methods i extracted, but perhaps they are for a different debugger?  When I commented them out I did not see any effect in realgud:pdb.
=> extract method for breakpoint stuff in realgud:track-from-region

realgud/debugger/trepan3k/init.el
In my debug mode, I'd like hitting "p" on a symbol to pretty print its value in the debugger via realgud:cmd-run-command. For this, the command hash must include an entry for "pp".
=> Add pprint to command hash

realgud/debugger/trepan3k/init.el
"until" was being added to the wrong hash table.
=> Add "until" to correct command hash

realgud/debugger/pdb/pdb.el
Since the command name "pdb" is already used by Emacs in gud.el
=> Remove pdb alias

realgud/common/cmds.el
BTW, I think `realgud:cmd-until` should also respect the line number. Otherwise it only stops at the next line.
In gdb, it seems sometimes `tbreak; c` is more accurate than `until`.
=> Add tbreak as per break

configure.ac
Hello!
This remove an extraneous trailing parenthesis in configure.ac.
I found the problem on GNU GuixSD which is now using Emacs 26; it seems older Emacs were more loose in evaluating the faulty Elisp snippet (as I didn't have this problem with Emacs 25 IIRC).
Thank you!
=> configure.ac: Fix NO_CHECK_EMACS_PACKAGES elisp.

realgud/debugger/pdb/pdb.el
Hi,
when I use pdb, the system usually tells me that no "pdb" command under MacOS.
I need to manually change pdb to `python -m pdb` instead. 
I also notice that some others face the same problem.
Could you please help me with this PR?
=> change pdb to python -m pdb.

INSTALL.md, configure.ac, realgud/common/file.el, realgud/common/track.el, realgud/common/utils.el, realgud/debugger/gdb/gdb.el, test/test-utils.el
1. track.el: gdb will generate ANSI escape sequences (emacs 25, Debian 9, gdb 7.12) into the comint
buffer which was causing the regex matches to fail resulting in no location tracking. Fix by
stripping the ANSI escape sequences when we extract the buffer text from the comint buffer.
2. gdb.el: When setting a breakpoint to a function, gdb by default displays a relative path, e.g.
(gdb) b functionName
Breakpoint 1 at 0x7fff607e4dd6: file dir/file.cpp, line 273.
where dir/file.cpp is relative which occurs when you compile using a relative path,
g++ -c dir/file.cpp
We want it to display
(gdb) b functionName
Breakpoint 1 at 0x7fff607e4dd6: file /abs/path/to/file.cpp, line 273.
which is achieved by setting "set filename-display absolute" at gdb startup.
3. file.el: Improve the prompt on file …
=> gdb: handle ANSI escape codes, relative paths, blacklist, and doc fix

realgud/debugger/gdb/gdb.el, realgud/debugger/gub/gub.el, realgud/debugger/pdb/pdb.el, realgud/debugger/trepan2/trepan2.el, realgud/debugger/trepan3k/trepan3k.el
Fixes <https://github.com/realgud/realgud/issues/269>.
The 'realgud:run-process' function was not defined in the context of
the gdb and gub debuggers, causing an error when running 'M-x
realgud:gdb', for example.
These are the important bits that fix the above problem:
* realgud/debugger/gdb/gdb.el: Require "../../common/run".
* realgud/debugger/gub/gub.el: Likewise.
The following changes are cosmetic, non-functional:
* realgud/debugger/gdb/gdb.el (realgud:run-process): Fix "file"
reference.
* realgud/debugger/gub/gub.el (realgud:run-process): Likewise.
* realgud/debugger/pdb/pdb.el (realgud:run-process): Likewise.
* realgud/debugger/trepan2/trepan2.el (realgud:run-process): Likewise.
* realgud/debugger/trepan3k/trepan3k.el (realgud:run-process): Likewise.
=> debuggers: Fix void realgud:run-process error in gdb and gub.

realgud/debugger/gdb/gdb.el, realgud/debugger/gub/gub.el
* realgud/debugger/gub/gub.el ("../../common/run"): Remove duplicate.
* realgud/debugger/gdb/gdb.el ("../../common/cmds"): Likewise.
=> debbugers: Fix duplicate require-relative-list for ../../common/run.

realgud/common/window.el
new option `realgud-window-split-orientation' can be set to:
- 'vertical: default value, behaves same as previous versions.
- 'horizontal: new, split window horizontally.
=> Add option to control orientation when splitting window.

realgud/common/buffer/locals.el, realgud/common/core.el, realgud/common/track.el
Locals buffer will not auto-recreate after being killed.
Autorefresh will work now after switching to new srcbuf.
=> Add proper cleanup for locals. Fix broken logic from b5ee91c.

realgud/common/track.el
Fixes https://github.com/realgud/realgud/issues/289
Hi,
Thanks for RealGUD. RealGUD's "short-key mode" is a nice replacement for gdb's "TUI Single Key Mode".
Removing the line https://github.com/realgud/realgud/blob/962b5af40c8970d09581613d67b1a5d99eaa39e7/realgud/common/track.el#L425 fixes the issue. The function containing that line is called by the "realgud-track-comint-output-filter-hook" which is added to the list of "comint-output-filter-functions".
This bug is not entirely deterministic. This bug is more likely to occur when the debugger command produces delayed output.
To reproduce this issue execute the following elisp code which creates a test python file containing code to delay the output and runs the realgud on the file
```
(progn
(with-temp-file "/tmp/test2.py"
(insert " …
```
=> Fix focus lose in source buffer after invoking debugger command.

realgud/common/track.el
Reverts realgud/realgud#293
@yberfrankc I've been trying this for the last week or so and the experience I get debugging Python is worse, it is not tracking source code locations enough to be annoying. 
(It may be that for gdb though this is better). At any rate we need something better than this and until such time when we have more people actively working on this my use takes precedence over broken behavior.
=> Revert "Fix focus lose in source buffer after invoking debugger command."

realgud/common/track-mode.el
In Emacs-26 "realgud-track-mode-map" had the keybindings of "comint-mode-map". This was accomplished
indirectly by copying the "shell-mode-map" which in turn copied from "comint-mode-map".
In Emacs-27 "shell-mode-map" no longer copies the "comint-mode-map" and this broke the
"realgud-track-mode-map"(https://github.com/emacs-mirror/emacs/commit/1204e7cb81093a42b781eb8c083af9d406de23e9)
To fix set the "comint-mode-map" as parent keymap.
Fixes https://github.com/realgud/realgud/issues/290
=> Include "comint-mode-map" bindings in "realgud-track-mode-map".

README.md
This adds a GNU ELPA badge to README.md.
You can see the badge here:
https://elpa.gnu.org/packages/realgud.svg
Thanks!
=> Add GNU ELPA badge to README.md

realgud/common/send.el
`src-file-name-raw` could be `nil`, resulting in an error when calling `file-remote-p` and causing this function to break.
=> Fix error in realgud-expand-format introduced in `d21f338`

realgud/common/track.el
If the eval message contains the chacater "%", then the call to message will error, because it's expecting format-string arguments. 
The recommended way to escape strings passed to message (according to `message's docstring) is to do the following: 
(message %s "the-string-%")
=> Escape the escape characters for message
